### ISSUE TITLE
memory consumption after loading checkpoint 

### ISSUE THREAD

**Issue by helson73** [OpenNMT/OpenNMT#33]
When the training is launched at the first time, everything works fine.
But after an interruption and reloading, it was stopped by an error "out of memory". (in GPU)
It seems like reloading checkpoint consumes more memory than initializing one. 
Could anyone give an advice about how to avoid this ? 
Many thanks.

**Comment by helson73** [comment]
Currently I set
checkpoint.models.encoder.modules[{1,2}].networkClones[k>1] = nil
checkpoint.models.decoder.modules[1].networkClones[k>1] = nil
and perform "collectgarbage()" to free VRAM.
I think saving model would be better to save only one clone.
BTW, if I do "collectgarbage()" during the training, is there any side effect ?

**Comment by helson73** [comment]
I guess this is caused by following reasons,
1. loading checkpoint costs VRAM.
2. after initializing model using checkpoint, checkpoint is not free and still uses memory.

solution:
add
`checkpoint = {}`
`collectgarbage()`
after initializing threads.
Everything works fine now.

**Comment by helson73** [comment]
I guess this is caused by following reasons,

loading checkpoint costs VRAM.
after initializing model using checkpoint, checkpoint is not free and still uses memory.
solution:
add
`checkpoint.models = nil`
`collectgarbage()`
after initializing threads.
Everything works fine now.

**Comment by helson73** [comment]
Another bug in train.lua, line 345-346
`      opt.learning_rate = checkpoint.info.learning_rate
      opt.optim_states = checkpoint.info.optim_states`
should be revised to
`      opt.learning_rate = checkpoint.info.learningRate
      opt.optim_states = checkpoint.info.optimStates`

**Comment by helson73** [comment]
It seems like saving checkpoint operation saves all clones of sequencer and pre-allocated buffers, which costs a lot hard disk space and memory (when initialized).

**Comment by guillaumekln** [comment]
Are you on the latest code revision? What are your training options? With the default options my retraining takes slightly less memory than the initial training.

Also, clones and pre-allocated Tensors are not saved on disk. See for example:

* https://github.com/OpenNMT/OpenNMT/blob/master/onmt/modules/Encoder.lua#L50 that exposes the data to save
* https://github.com/OpenNMT/OpenNMT/blob/master/onmt/train/Checkpoint.lua#L25 that retrieves them before saving

**Comment by helson73** [comment]
@guillaumekln my option is 'brnn=true, brnn_merge=concat'
after loading checkpoint,
checkpoint.models.encoder.modules[1].networkClones has "maxlen" clones, each contains a gModule.

**Comment by guillaumekln** [comment]
Oh, you are right. The serialization of the bidirectional encoder was incorrect and included clones and preallocated tensors.

Thanks for reporting!
